"""
Generate a self-contained, one-command installer for the Kratos sub-agent.

This turns the dev-only "copy the five bundle files onto the target and run
``python3 -m subagent.agent`` by hand" into a single POSIX-``sh`` script that a
user runs once on the target. The five stdlib-only bundle files
(``agent``/``protocol``/``collector``/``signing``/``whitelist``) are embedded as
base64 blobs, so the generated script needs **no network, no PyPI, and no
hosting endpoint** -- it writes the bundle, installs a systemd service
(``Restart=always``; a ``systemctl --user`` fallback when not root, a plain
background start when there's no systemd at all), and starts it.

What this does NOT do, on purpose:

- It never connects to a target, never runs anything, never takes SSH
  credentials. It only produces text (the installer script). Getting that
  script onto the target and running it once is the operator's single
  bootstrap step -- the same unavoidable step every agent-based tool has.
- It never enables capability 2 (direct execution). The generated service runs
  the agent with telemetry only; ``--enable-execution`` is deliberately never
  emitted here.

Forward-compatible: when a ``kratos-agent`` PyPI package and a hosted
``pair.sh`` land (the pre-publication packaging step), the same pairing flow can
emit a ``curl ... | sh`` one-liner instead of this embedded script -- nothing
about the UI flow around it changes.
"""
from __future__ import annotations

import base64
import textwrap
from datetime import datetime, timezone
from pathlib import Path

# The five stdlib-only files that make up the deployable agent bundle. They must
# stay siblings in a ``subagent/`` package directory on the target (see
# agent.py's module docstring). Order is irrelevant -- each is written
# independently -- but agent.py is listed first as the entry point.
BUNDLE_FILES: tuple[str, ...] = (
    "agent.py",
    "protocol.py",
    "collector.py",
    "signing.py",
    "whitelist.py",
    "ceiling.py",
)

DEFAULT_SERVICE_NAME = "kratos-subagent"
DEFAULT_CORE_PORT = 8765

# A minimal package ``__init__`` for the on-target bundle. Deliberately NOT the
# repo's own ``subagent/__init__.py`` -- the bundle is standalone and should not
# carry this repo's narrative docstring or ever grow a non-stdlib import.
_BUNDLE_INIT = '"""Kratos sub-agent bundle (stdlib-only, read-only telemetry).\n\nGenerated by kratos.subagent.installer -- do not edit by hand.\n"""\n'

# The heredoc delimiter used for each embedded blob. Fixed and distinctive; the
# blobs are base64, so this token can never appear inside one.
_EOF = "KRATOS_SUBAGENT_BLOB_EOF"


class InstallerError(RuntimeError):
    """Raised when the installer cannot be generated (e.g. a bundle file is missing)."""


def _bundle_dir() -> Path:
    return Path(__file__).resolve().parent


def read_bundle_files() -> dict[str, str]:
    """Read the five bundle files from the installed package.

    Reads from this module's own directory, so it always embeds exactly the
    agent code that ships alongside this installer -- never a stale copy.
    """
    out: dict[str, str] = {}
    base = _bundle_dir()
    for name in BUNDLE_FILES:
        path = base / name
        try:
            out[name] = path.read_text(encoding="utf-8")
        except OSError as exc:  # pragma: no cover - defensive; the files ship with the package
            raise InstallerError(f"cannot read bundle file {name!r}: {exc}") from exc
    return out


def _b64_block(text: str) -> str:
    """Base64-encode ``text`` and wrap it to fixed-width lines for the heredoc."""
    raw = base64.b64encode(text.encode("utf-8")).decode("ascii")
    return "\n".join(textwrap.wrap(raw, width=76)) or ""


def _sh_squote(value: str) -> str:
    """Single-quote a value for safe embedding in the POSIX-sh script."""
    return "'" + value.replace("'", "'\\''") + "'"


def generate_installer(
    core_host: str,
    pairing_code: str,
    *,
    core_port: int = DEFAULT_CORE_PORT,
    service_name: str = DEFAULT_SERVICE_NAME,
) -> str:
    """Return a self-contained POSIX-``sh`` installer for the sub-agent.

    ``core_host``/``core_port`` are the address the target will DIAL to reach
    this Kratos core (the agent always dials out; the target opens no inbound
    port). ``pairing_code`` is a single-use code from
    ``SubAgentStore.create_pairing_code`` -- it is only consumed on the agent's
    first successful connect; once a token is saved the code is ignored, so it
    is safe to leave in the persistent service's command line.
    """
    if not core_host or not str(core_host).strip():
        raise InstallerError("core_host is required")
    if not pairing_code or not str(pairing_code).strip():
        raise InstallerError("pairing_code is required")
    try:
        port = int(core_port)
    except (TypeError, ValueError) as exc:
        raise InstallerError(f"invalid core_port: {core_port!r}") from exc
    if not (0 < port < 65536):
        raise InstallerError(f"core_port out of range: {port}")

    files = read_bundle_files()
    files_with_init = {"__init__.py": _BUNDLE_INIT, **files}

    blobs: list[str] = []
    for rel_name, content in files_with_init.items():
        blobs.append(
            f"write_file subagent/{rel_name} <<'{_EOF}'\n{_b64_block(content)}\n{_EOF}"
        )
    blob_section = "\n".join(blobs)

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    host_q = _sh_squote(str(core_host).strip())
    code_q = _sh_squote(str(pairing_code).strip())
    svc_q = _sh_squote(service_name)

    return _TEMPLATE.format(
        generated_at=generated_at,
        core_host=str(core_host).strip(),
        core_port=port,
        host_q=host_q,
        port=port,
        code_q=code_q,
        svc_q=svc_q,
        blob_section=blob_section,
        eof=_EOF,
    )


# NOTE: this is a plain str.format template. The embedded shell uses ``${{...}}``
# for its own variables (doubled braces survive .format); Python fields are the
# single-brace names above.
_TEMPLATE = """\
#!/bin/sh
# Kratos sub-agent installer -- generated {generated_at}
#
# Installs a small, read-only telemetry agent that dials out to this Kratos
# core at {core_host}:{core_port} and forwards observation-only snapshots.
# The target opens NO inbound port. Direct execution (capability 2) is NOT
# enabled by this installer.
#
# Run once on the target:  sh kratos-subagent-install.sh
set -eu

CORE_HOST={host_q}
CORE_PORT={port}
PAIR_CODE={code_q}
SERVICE_NAME={svc_q}

log() {{ printf '%s\\n' "$*"; }}
die() {{ printf 'error: %s\\n' "$*" >&2; exit 1; }}

PY=$(command -v python3 || true)
[ -n "$PY" ] || die "python3 is required on the target but was not found"
command -v base64 >/dev/null 2>&1 || die "base64 is required on the target but was not found"

# Decide where to install and whether we can manage a system service.
# Priority: real root -> passwordless sudo -> unprivileged user install.
SUDO=""
if [ "$(id -u)" = "0" ]; then
    INSTALL_DIR=/opt/kratos-subagent
    MODE=system
elif command -v sudo >/dev/null 2>&1 && sudo -n true >/dev/null 2>&1; then
    INSTALL_DIR=/opt/kratos-subagent
    MODE=system
    SUDO="sudo"
else
    INSTALL_DIR="$HOME/.kratos-subagent"
    MODE=user
fi
STATE_FILE="$INSTALL_DIR/state.json"

log "Installing Kratos sub-agent into $INSTALL_DIR (mode: $MODE)"
$SUDO mkdir -p "$INSTALL_DIR/subagent"

# write_file <relative-path> : base64 body on stdin -> decoded file on disk.
write_file() {{
    _dest="$INSTALL_DIR/$1"
    if [ -n "$SUDO" ]; then
        base64 -d | $SUDO tee "$_dest" >/dev/null
    else
        base64 -d > "$_dest"
    fi
}}

{blob_section}

log "Bundle written."

EXEC_CMD="$PY -m subagent.agent --core-host $CORE_HOST --core-port $CORE_PORT --pair $PAIR_CODE --state-file $STATE_FILE"

start_plain() {{
    log "systemd not available -- starting in the background (will NOT survive a reboot)."
    log "To make it permanent, re-run this on a systemd host, or add your own init script."
    # shellcheck disable=SC2086
    ( cd "$INSTALL_DIR" && nohup $EXEC_CMD >"$INSTALL_DIR/agent.log" 2>&1 & )
    log "Started. Logs: $INSTALL_DIR/agent.log"
}}

if [ "$MODE" = "system" ]; then
    if ! command -v systemctl >/dev/null 2>&1; then
        start_plain
        exit 0
    fi
    UNIT=/etc/systemd/system/$SERVICE_NAME.service
    $SUDO sh -c "cat > $UNIT" <<UNIT_EOF
[Unit]
Description=Kratos sub-agent (read-only telemetry)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$INSTALL_DIR
ExecStart=$EXEC_CMD
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT_EOF
    $SUDO systemctl daemon-reload
    $SUDO systemctl enable --now "$SERVICE_NAME.service"
    log "Service installed and started: $SERVICE_NAME"
    log "  status: $SUDO systemctl status $SERVICE_NAME"
    log "  logs:   $SUDO journalctl -u $SERVICE_NAME -f"
else
    if ! command -v systemctl >/dev/null 2>&1; then
        start_plain
        exit 0
    fi
    UNIT_DIR="$HOME/.config/systemd/user"
    mkdir -p "$UNIT_DIR"
    UNIT="$UNIT_DIR/$SERVICE_NAME.service"
    cat > "$UNIT" <<UNIT_EOF
[Unit]
Description=Kratos sub-agent (read-only telemetry)
After=network-online.target

[Service]
Type=simple
WorkingDirectory=$INSTALL_DIR
ExecStart=$EXEC_CMD
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
UNIT_EOF
    systemctl --user daemon-reload
    systemctl --user enable --now "$SERVICE_NAME.service" || {{
        start_plain
        exit 0
    }}
    log "User service installed and started: $SERVICE_NAME"
    log "  It runs while you are logged in. To keep it running after logout:"
    log "    sudo loginctl enable-linger $(id -un)"
    log "  status: systemctl --user status $SERVICE_NAME"
    log "  logs:   journalctl --user -u $SERVICE_NAME -f"
fi

log ""
log "Done. The sub-agent is starting and will check in with Kratos shortly."
"""
