"""
Generate a self-contained, one-command installer for the Kratos sub-agent.

This turns the dev-only "copy the five bundle files onto the target and run
``python3 -m subagent.agent`` by hand" into a single POSIX-``sh`` script that a
user runs once on the target. The five stdlib-only bundle files
(``agent``/``protocol``/``collector``/``signing``/``whitelist``) are embedded as
base64 blobs, so the generated script needs **no network, no PyPI, and no
hosting endpoint** -- it writes the bundle, installs a systemd service
(``Restart=always``; a ``systemctl --user`` fallback when not root, a plain
background start when there's no systemd at all), and starts it.

What this does NOT do, on purpose:

- It never connects to a target, never runs anything, never takes SSH
  credentials. It only produces text (the installer script). Getting that
  script onto the target and running it once is the operator's single
  bootstrap step -- the same unavoidable step every agent-based tool has.
- It never enables capability 2 (direct execution). The generated service runs
  the agent with telemetry only; ``--enable-execution`` is deliberately never
  emitted here.

Forward-compatible: when a ``kratos-agent`` PyPI package and a hosted
``pair.sh`` land (the pre-publication packaging step), the same pairing flow can
emit a ``curl ... | sh`` one-liner instead of this embedded script -- nothing
about the UI flow around it changes.
"""
from __future__ import annotations

import base64
import textwrap
from datetime import datetime, timezone
from pathlib import Path

# The five stdlib-only files that make up the deployable agent bundle. They must
# stay siblings in a ``subagent/`` package directory on the target (see
# agent.py's module docstring). Order is irrelevant -- each is written
# independently -- but agent.py is listed first as the entry point.
BUNDLE_FILES: tuple[str, ...] = (
    "agent.py",
    "protocol.py",
    "collector.py",
    "signing.py",
    "whitelist.py",
    "ceiling.py",
)

DEFAULT_SERVICE_NAME = "kratos-subagent"
DEFAULT_CORE_PORT = 8765

# A minimal package ``__init__`` for the on-target bundle. Deliberately NOT the
# repo's own ``subagent/__init__.py`` -- the bundle is standalone and should not
# carry this repo's narrative docstring or ever grow a non-stdlib import.
_BUNDLE_INIT = '"""Kratos sub-agent bundle (stdlib-only, read-only telemetry).\n\nGenerated by kratos.subagent.installer -- do not edit by hand.\n"""\n'

# The heredoc delimiter used for each embedded blob. Fixed and distinctive; the
# blobs are base64, so this token can never appear inside one.
_EOF = "KRATOS_SUBAGENT_BLOB_EOF"


class InstallerError(RuntimeError):
    """Raised when the installer cannot be generated (e.g. a bundle file is missing)."""


def _bundle_dir() -> Path:
    return Path(__file__).resolve().parent


def read_bundle_files() -> dict[str, str]:
    """Read the five bundle files from the installed package.

    Reads from this module's own directory, so it always embeds exactly the
    agent code that ships alongside this installer -- never a stale copy.
    """
    out: dict[str, str] = {}
    base = _bundle_dir()
    for name in BUNDLE_FILES:
        path = base / name
        try:
            out[name] = path.read_text(encoding="utf-8")
        except OSError as exc:  # pragma: no cover - defensive; the files ship with the package
            raise InstallerError(f"cannot read bundle file {name!r}: {exc}") from exc
    return out


def _b64_block(text: str) -> str:
    """Base64-encode ``text`` and wrap it to fixed-width lines for the heredoc."""
    raw = base64.b64encode(text.encode("utf-8")).decode("ascii")
    return "\n".join(textwrap.wrap(raw, width=76)) or ""


def _sh_squote(value: str) -> str:
    """Single-quote a value for safe embedding in the POSIX-sh script."""
    return "'" + value.replace("'", "'\\''") + "'"


def generate_installer(
    core_host: str,
    pairing_code: str | None,
    *,
    core_port: int = DEFAULT_CORE_PORT,
    service_name: str = DEFAULT_SERVICE_NAME,
    upgrade: bool = False,
) -> str:
    """Return a self-contained POSIX-``sh`` installer for the sub-agent.

    ``core_host``/``core_port`` are the address the target will DIAL to reach
    this Kratos core (the agent always dials out; the target opens no inbound
    port). ``pairing_code`` is a single-use code from
    ``SubAgentStore.create_pairing_code`` -- it is only consumed on the agent's
    first successful connect; once a token is saved the code is ignored, so it
    is safe to leave in the persistent service's command line.

    Re-running on a box that already has an agent is safe either way:
    - with a pairing code (the default), the box starts a FRESH identity -- the
      old state file is kept aside (never deleted) and the new code is used,
      which is what re-pairing needs;
    - with ``upgrade=True`` (no code), the existing identity is kept and only
      the agent code is replaced -- the path for updating an agent in place.
    Either way the service is RESTARTED, so the new code actually runs.
    """
    if not core_host or not str(core_host).strip():
        raise InstallerError("core_host is required")
    if upgrade:
        pairing_code = ""
    elif not pairing_code or not str(pairing_code).strip():
        raise InstallerError("pairing_code is required (or use upgrade=True to keep the existing pairing)")
    try:
        port = int(core_port)
    except (TypeError, ValueError) as exc:
        raise InstallerError(f"invalid core_port: {core_port!r}") from exc
    if not (0 < port < 65536):
        raise InstallerError(f"core_port out of range: {port}")

    files = read_bundle_files()
    files_with_init = {"__init__.py": _BUNDLE_INIT, **files}

    blobs: list[str] = []
    for rel_name, content in files_with_init.items():
        blobs.append(
            f"write_file subagent/{rel_name} <<'{_EOF}'\n{_b64_block(content)}\n{_EOF}"
        )
    blob_section = "\n".join(blobs)

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    host_q = _sh_squote(str(core_host).strip())
    code_q = _sh_squote(str(pairing_code or "").strip())
    svc_q = _sh_squote(service_name)

    return _TEMPLATE.format(
        generated_at=generated_at,
        core_host=str(core_host).strip(),
        core_port=port,
        host_q=host_q,
        port=port,
        code_q=code_q,
        svc_q=svc_q,
        upgrade="1" if upgrade else "0",
        blob_section=blob_section,
        eof=_EOF,
    )


# NOTE: this is a plain str.format template. The embedded shell uses ``${{...}}``
# for its own variables (doubled braces survive .format); Python fields are the
# single-brace names above.
_TEMPLATE = """\
#!/bin/sh
# Kratos sub-agent installer -- generated {generated_at}
#
# Installs a small, read-only telemetry agent that dials out to this Kratos
# core at {core_host}:{core_port} and forwards observation-only snapshots.
# The target opens NO inbound port. Direct execution (capability 2) is NOT
# enabled by this installer.
#
# Run once on the target:  sh kratos-subagent-install.sh
# Safe to re-run: it replaces the agent code and restarts it.
set -eu

CORE_HOST={host_q}
CORE_PORT={port}
PAIR_CODE={code_q}
UPGRADE={upgrade}
SERVICE_NAME={svc_q}

log() {{ printf '%s\\n' "$*"; }}
# Machine-readable failure line (Kratos classifies these), then a plain one.
die() {{ printf 'KRATOS_INSTALL_ERROR: %s: %s\\n' "$1" "$2" >&2; printf 'error: %s\\n' "$2" >&2; exit 1; }}

PY=$(command -v python3 || true)
[ -n "$PY" ] || die no_python "python3 is required on the target but was not found"
"$PY" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 8) else 1)' \\
    || die python_too_old "python3 is too old ($("$PY" -V 2>&1)); the agent needs Python 3.8 or newer"
command -v base64 >/dev/null 2>&1 || die no_base64 "base64 is required on the target but was not found"

# Decide where to install and whether we can manage a system service.
# Priority: real root -> passwordless sudo -> unprivileged user install.
SUDO=""
if [ "$(id -u)" = "0" ]; then
    INSTALL_DIR=/opt/kratos-subagent
    MODE=system
elif command -v sudo >/dev/null 2>&1 && sudo -n true >/dev/null 2>&1; then
    INSTALL_DIR=/opt/kratos-subagent
    MODE=system
    SUDO="sudo"
else
    INSTALL_DIR="$HOME/.kratos-subagent"
    MODE=user
fi
STATE_FILE="$INSTALL_DIR/state.json"

if [ "$UPGRADE" = "1" ]; then
    $SUDO grep -q '"token": "' "$STATE_FILE" 2>/dev/null || die not_paired "this box has no paired Kratos agent to upgrade ($STATE_FILE missing) -- use a pairing installer instead"
    log "Upgrading the Kratos sub-agent in $INSTALL_DIR (mode: $MODE); keeping its pairing."
elif $SUDO test -e "$STATE_FILE"; then
    # Re-pairing: a saved token would make the agent ignore the new code, so
    # move the old identity aside (kept, never deleted) and start fresh.
    OLD="$STATE_FILE.replaced-$(date +%s)"
    $SUDO mv "$STATE_FILE" "$OLD"
    log "Found an existing Kratos sub-agent here; its old identity was moved to $OLD and this box will pair again."
fi

log "Installing Kratos sub-agent into $INSTALL_DIR (mode: $MODE)"
$SUDO mkdir -p "$INSTALL_DIR/subagent" || die write_failed "could not create $INSTALL_DIR"

# write_file <relative-path> : base64 body on stdin -> decoded file on disk.
write_file() {{
    _dest="$INSTALL_DIR/$1"
    if [ -n "$SUDO" ]; then
        base64 -d | $SUDO tee "$_dest" >/dev/null || die write_failed "could not write $_dest (disk full or read-only?)"
    else
        base64 -d > "$_dest" || die write_failed "could not write $_dest (disk full or read-only?)"
    fi
}}

{blob_section}

log "Bundle written."

EXEC_CMD="$PY -m subagent.agent --core-host $CORE_HOST --core-port $CORE_PORT --state-file $STATE_FILE"
[ -n "$PAIR_CODE" ] && EXEC_CMD="$EXEC_CMD --pair $PAIR_CODE"

start_plain() {{
    log "systemd not available -- starting in the background (will NOT survive a reboot)."
    log "To make it permanent, re-run this on a systemd host, or add your own init script."
    PIDFILE="$INSTALL_DIR/agent.pid"
    # Stop a previous background agent from an earlier run (never two at once).
    if [ -f "$PIDFILE" ]; then
        OLD_PID=$(cat "$PIDFILE" 2>/dev/null || true)
        if [ -n "$OLD_PID" ] && grep -q subagent.agent "/proc/$OLD_PID/cmdline" 2>/dev/null; then
            $SUDO kill "$OLD_PID" 2>/dev/null || true
            log "Stopped the previous background agent (pid $OLD_PID)."
        fi
    fi
    LOGFILE="$INSTALL_DIR/agent.log"
    START="$INSTALL_DIR/start.sh"
    # Fully detached (stdin from /dev/null, output to the log) so the ssh
    # session that ran this installer can close and the agent outlives it.
    # Written to start.sh so the exact same launch can run again at boot.
    # With sudo it runs as root: the install dir is root's.
    printf '#!/bin/sh\\n# Starts the Kratos sub-agent in the background (no systemd on this box).\\ncd %s || exit 1\\nnohup %s >%s 2>&1 </dev/null &\\necho $! > %s\\n' \\
        "'$INSTALL_DIR'" "$EXEC_CMD" "'$LOGFILE'" "'$PIDFILE'" | $SUDO tee "$START" >/dev/null \\
        || die write_failed "could not write $START"
    $SUDO chmod 755 "$START" 2>/dev/null || true
    $SUDO sh "$START" || die start_failed "could not start the agent in the background"
    sleep 2
    NEW_PID=$($SUDO cat "$PIDFILE" 2>/dev/null || true)
    if [ -z "$NEW_PID" ] || ! $SUDO kill -0 "$NEW_PID" 2>/dev/null; then
        die start_failed "the agent exited right after starting: $($SUDO tail -n 3 "$LOGFILE" 2>/dev/null | tr '\\n' ' ')"
    fi
    log "Started (pid $NEW_PID). Logs: $LOGFILE"
    # Survive a reboot where the box's own init allows it without systemd:
    # OpenRC (Alpine etc.) runs /etc/local.d/*.start at boot.
    BOOT=no
    if [ "$MODE" = "system" ] && [ -d /etc/local.d ] && command -v rc-update >/dev/null 2>&1; then
        printf '#!/bin/sh\\nexec sh %s\\n' "'$START'" | $SUDO tee /etc/local.d/$SERVICE_NAME.start >/dev/null \\
            && $SUDO chmod 755 /etc/local.d/$SERVICE_NAME.start \\
            && $SUDO rc-update add local default >/dev/null 2>&1 && BOOT=yes
    fi
    if [ "$BOOT" = "yes" ]; then
        log "It will start again at boot (OpenRC: /etc/local.d/$SERVICE_NAME.start)."
    else
        log "It will NOT start again after a reboot. To start it by hand: $SUDO sh $START"
    fi
    printf 'KRATOS_INSTALL_OK mode=%s service=none dir=%s boot=%s start=%s\\n' "$MODE" "$INSTALL_DIR" "$BOOT" "$START"
}}

# A crashing agent under Restart=always looks "installed"; make sure it stays up.
check_service() {{
    sleep 3
    if ! $1 is-active --quiet "$SERVICE_NAME.service"; then
        die start_failed "the $SERVICE_NAME service is not running: $($2 -u "$SERVICE_NAME" -n 3 --no-pager -o cat 2>/dev/null | tr '\\n' ' ')"
    fi
}}

if [ "$MODE" = "system" ]; then
    if ! command -v systemctl >/dev/null 2>&1 || [ ! -d /run/systemd/system ]; then
        start_plain
        exit 0
    fi
    UNIT=/etc/systemd/system/$SERVICE_NAME.service
    $SUDO sh -c "cat > $UNIT" <<UNIT_EOF
[Unit]
Description=Kratos sub-agent (read-only telemetry)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$INSTALL_DIR
ExecStart=$EXEC_CMD
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT_EOF
    $SUDO systemctl daemon-reload
    $SUDO systemctl enable "$SERVICE_NAME.service"
    # restart, not just enable --now: an already-running agent must load the
    # new code and identity.
    $SUDO systemctl restart "$SERVICE_NAME.service"
    check_service "$SUDO systemctl" "$SUDO journalctl"
    log "Service installed and started: $SERVICE_NAME"
    log "  status: $SUDO systemctl status $SERVICE_NAME"
    log "  logs:   $SUDO journalctl -u $SERVICE_NAME -f"
    printf 'KRATOS_INSTALL_OK mode=system service=%s dir=%s\\n' "$SERVICE_NAME" "$INSTALL_DIR"
else
    if ! command -v systemctl >/dev/null 2>&1 || ! systemctl --user show-environment >/dev/null 2>&1; then
        start_plain
        exit 0
    fi
    UNIT_DIR="$HOME/.config/systemd/user"
    mkdir -p "$UNIT_DIR"
    UNIT="$UNIT_DIR/$SERVICE_NAME.service"
    cat > "$UNIT" <<UNIT_EOF
[Unit]
Description=Kratos sub-agent (read-only telemetry)
After=network-online.target

[Service]
Type=simple
WorkingDirectory=$INSTALL_DIR
ExecStart=$EXEC_CMD
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
UNIT_EOF
    systemctl --user daemon-reload
    systemctl --user enable "$SERVICE_NAME.service" && systemctl --user restart "$SERVICE_NAME.service" || {{
        start_plain
        exit 0
    }}
    check_service "systemctl --user" "journalctl --user"
    log "User service installed and started: $SERVICE_NAME"
    LINGER=yes
    if [ "$(loginctl show-user "$(id -un)" -p Linger --value 2>/dev/null)" != "yes" ]; then
        LINGER=no
        log "  It runs while you are logged in. To keep it running after logout:"
        log "    sudo loginctl enable-linger $(id -un)"
    fi
    log "  status: systemctl --user status $SERVICE_NAME"
    log "  logs:   journalctl --user -u $SERVICE_NAME -f"
    printf 'KRATOS_INSTALL_OK mode=user service=%s dir=%s linger=%s user=%s\\n' "$SERVICE_NAME" "$INSTALL_DIR" "$LINGER" "$(id -un)"
fi

log ""
log "Done. The sub-agent is starting and will check in with Kratos shortly."
"""


def uninstall_command(service_name: str = DEFAULT_SERVICE_NAME) -> str:
    """One command, run ON the target, that stops and removes the agent
    whichever way it was installed (system service, user service, or a
    background process). Safe to run when parts are already gone."""
    svc = service_name
    # $S is sudo unless already root (a root shell may have no sudo at all).
    return (
        'S=sudo; [ "$(id -u)" = 0 ] && S=; '
        f"if [ -f /etc/systemd/system/{svc}.service ]; then $S systemctl disable --now {svc}; "
        f"$S rm -f /etc/systemd/system/{svc}.service; $S systemctl daemon-reload; fi; "
        f"systemctl --user disable --now {svc} 2>/dev/null; rm -f ~/.config/systemd/user/{svc}.service; "
        "[ -f /opt/kratos-subagent/agent.pid ] && $S kill $(cat /opt/kratos-subagent/agent.pid) 2>/dev/null; "
        "[ -f ~/.kratos-subagent/agent.pid ] && kill $(cat ~/.kratos-subagent/agent.pid) 2>/dev/null; "
        f"$S rm -f /etc/local.d/{svc}.start; "
        "$S rm -rf /opt/kratos-subagent; rm -rf ~/.kratos-subagent"
    )
